apiVersion: v1
kind: ServiceAccount
metadata:
  name: hardened-pod-sa
  namespace: fridhemfighters
---
apiVersion: v1
kind: Pod
metadata:
  name: hardened-pod
  namespace: fridhemfighters
  labels:
    app: hardened-pod
    team: fridhemfighters
spec:
  serviceAccountName: hardened-pod-sa
  containers:
    - name: app
      image: nginx:1.27.5
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL
      resources:
        limits:
          cpu: "200m"
          memory: "256Mi"
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 10
